### ISSUE TITLE
Stealthburner Knomi 2

### ISSUE THREAD

**Issue by Zay1Million** [bigtreetech/Universal-Turbo-Kit#1]
The Knomi 2 does not fit in the new tool head

**Comment by BTTJUSTIN** [comment]
Hi,Thanks for your reporting .
Please describe in detail which area on the printed part is causing trouble. the included print model for sb is designed for knomi v2,here is the installed assembly.  please check that your print has no imperfections. 
![图片](https://github.com/bigtreetech/Universal-Turbo-Kit/assets/169997478/d33729ca-5bf2-4be0-b14c-effaad50f01f)
![图片](https://github.com/bigtreetech/Universal-Turbo-Kit/assets/169997478/935f6953-b7d6-4de7-a9b3-7dce98df78d2)
![图片](https://github.com/bigtreetech/Universal-Turbo-Kit/assets/169997478/6304a2e5-505d-4c92-bcd8-85f229b556cd)

**Comment by Zay1Million** [comment]
From the downloaded file the Knomi 2 device would not fit into the slot on the stealthburner tool head. I made many attempts to work around the issue without success. I'd like to think that my printer is well-tuned, used an X1C to print. However, I was able to find a remixed file on the printables website. Thanks for addressing my concern.

**Comment by BTTJUSTIN** [comment]
Hi，
Thanks for your reply.
1.Please send me the picture on this phenomenon"the Knomi 2 device would not fit into the slot on the stealthburner tool head."
2.And please send me the link of the  a remixed file on the printables website. 
We will check on it

**Comment by Zay1Million** [comment]
I already have my toolhead assembled and don't want to take it apart again to demonstrate, but the link below is the remixed file that I used. Thanks again!

https://www.printables.com/model/891528-stealthburner-cpap-knomi-2-sb2209-or-sb2240-3do-no

**Comment by BTTJUSTIN** [comment]
Hi ,thanks for your sharing, it is glad to hear that you figured it out

**Comment by StreckerCM** [comment]
This issue still exists with the KNOMI 2.  

![image](https://github.com/user-attachments/assets/d288f333-f60e-4712-bbaa-275555ae2c74)

![image](https://github.com/user-attachments/assets/6200b58f-f3f9-46fd-b29e-82718106825c)

![image](https://github.com/user-attachments/assets/01e082a5-aa5b-4316-8f87-5315a8841b03)

![image](https://github.com/user-attachments/assets/ec2a515c-e952-4a69-83e5-1dce7772bf08)

![image](https://github.com/user-attachments/assets/71c514f4-e28c-4011-9cd7-66b64f3b46ac)

**Comment by bigtreetech** [comment]
> This issue still exists with the KNOMI 2.
> 

Looks as if you've printed the wrong file. That is for KNOMI 1. This will work for KNOMI 2. https://www.printables.com/model/891528-stealthburner-cpap-knomi-2-sb2209-or-sb2240-3do-no

**Comment by StreckerCM** [comment]
Unfortunately there isn't a STEP file for that model and Fusion 360 wont let me modify the body it generates from the STL without giving geometry calculation errors.  The solution for those errors according to their help documents are to use the STEP file. I was trying to modify it to work with the 3DO nozzle cam V2.
