### ISSUE TITLE
Stealthburner Knomi 2 -  NO nozcam

### ISSUE THREAD

**Issue by fabrimp** [bigtreetech/Universal-Turbo-Kit#2]
Request Stealthburner Knomi 2 - NO nozecam version.

I want to use my turbo kit with Knomi 2 but do not intend to install a nozecam. The current mounting completely blocks my view of what my printer is doing.

**Comment by BTTJUSTIN** [comment]
This is the link to the model that the stealthburner part is based on, you can download step file from here and modify it to your liking
https://www.printables.com/model/574324-stealthburner-knomi-can-sb22092240-cpap-nozzle-cam/files

**Comment by BTTJUSTIN** [comment]
The documentation has now been updated.
